apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test
  name: hello-boot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nexus.pl.ctl.io:16002/io.clc/spring-boot-hello:latest
        imagePullPolicy: Always
        name: hello-boot
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: hello-boot
  namespace: default
spec:
  ports:
  - nodePort: 30253
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}