apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
  name: hello-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: rmcneal/boot:latest
        imagePullPolicy: Always
        name: hello-boot
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 8
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: hello-boot
spec:
  ports:
  - nodePort: 30364
    name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  sessionAffinity: None
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: boot-monitor
  namespace: default
  labels:
    app: demo
    k8s-apps: demo
spec:
  # ServiceMonitors can monitor items in other namespaces
  namespaceSelector:
    matchNames:
    - default
  jobLabel: hello-boot-monitor
  selector:
    matchLabels:
      app: demo
  endpoints:
  - port: web
    interval: 10s
    path: /prometheus