apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: boot-monitor
  labels:
    app: demo
    k8s-apps: demo
spec:
  jobLabel: hello-boot-monitor
  selector:
    matchLabels:
      app: demo
  endpoints:
  - port: web
    interval: 10s
    path: /prometheus