apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
  name: hello-boot
  namespace: rm-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: nexus.pl.ctl.io:16000/io.clc/spring-boot-hello:latest
        imagePullPolicy: Always
        name: hello-boot
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 8
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rm-test
  name: hello-boot
  namespace: example
spec:
  ports:
  - nodePort: 30255
    name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}